version: '3.8'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - .env
    depends_on:
      - mongo
  mongo:
    image: 'mongo:7.0.5'
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=playlist
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password

